services:
  backend:
    image: softcat477/pweb-backend:v1.1.0
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:80/health"]
      interval: 2m30s
      timeout: 15s
      retries: 3
      start_period: 5m
